spring.application.name=traffic-violation-api
spring.datasource.url=jdbc:postgresql://localhost:5432/trafficdb
spring.datasource.username=postgres
spring.datasource.password=sheetu@11229

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect