spring.application.name=traffic-violation-api
spring.datasource.url=jdbc:postgresql://localhost:5432/trafficdb
spring.datasource.username=postgres
spring.datasource.password=sheetu@11229

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# Include error messages in the JSON error response so frontend can display them
server.error.include-message=always
server.error.include-binding-errors=always

google.client-id=${GOOGLE_CLIENT_ID:791551102242-ld02kh11bva5atogkm3r6c8vsol347t5.apps.googleusercontent.com}
